# Generated by Django 5.2 on 2025-04-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
